In [1]:
input_layer_size  = 400; 
num_labels = 10;         

load('ex3data1.mat'); % training data stored in arrays X, y
m = size(X, 1);

% Testing Cost Function
theta_t = [-2; -1; 1; 2];
X_t = [ones(5,1) reshape(1:15,5,3)/10];
y_t = ([1;0;1;0;1] >= 0.5);
lambda_t = 3;
[J grad] = lrCostFunction(theta_t, X_t, y_t, lambda_t);

%% ============ Part 2b: One-vs-All Training ============
fprintf('\nTraining One-vs-All Logistic Regression...\n')

lambda = 0.1;
[all_theta] = oneVsAll(X, y, num_labels, lambda);

fprintf('Program paused. Press enter to continue.\n');
pause;


%% ================ Part 3: Predict for One-Vs-All ================

pred = predictOneVsAll(all_theta, X);

fprintf('\nTraining Set Accuracy: %f\n', mean(double(pred == y)) * 100);




Training One-vs-All Logistic Regression...
Iteration    50 | Cost: 1.375420e-02
Iteration    50 | Cost: 5.725220e-02
Iteration    50 | Cost: 6.390787e-02
Iteration    50 | Cost: 3.632560e-02
Iteration    50 | Cost: 6.187453e-02
Iteration    50 | Cost: 2.211661e-02
Iteration    50 | Cost: 3.303378e-02
Iteration    50 | Cost: 8.438209e-02
Iteration    50 | Cost: 7.981973e-02
Iteration    50 | Cost: 9.905213e-03
Program paused. Press enter to continue.
Paused, enter any value to continue

Training Set Accuracy: 0.000000


In [8]:
inputs = [ones(5000, 1), X]';

In [10]:
size(inputs), size(all_theta)

ans =

    401   5000

ans =

    10   401



In [26]:
predictions = sigmoid(all_theta*inputs);

In [27]:
size(predictions)

ans =

     10   5000



In [28]:
[val, indx] = max(predictions);
indx = indx';

In [29]:
sum(indx == y)/5000

ans =  0.95140


In [61]:
load("ex3weights.mat");

In [62]:
size(Theta1), size(Theta2), size(X)

ans =

    25   401

ans =

   10   26

ans =

   5000    401



In [42]:
X = [ones(5000, 1), X];

In [43]:
size(X);

In [48]:
l1 = X * Theta1';

In [49]:
size(outputs)

ans =

   5000     25



In [50]:
l1 = [ones(size(l1, 1), 1), l1];
l2 = l1*Theta2';

In [54]:
[val, indx] = max(l2');

In [57]:
predictions = indx';

In [58]:
predictions

predictions =

   10
   10
    8
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
    8
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
    8
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
    8
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
    8
   10
    8
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
    8
   10
   10
   10
   10
   10
   10
   10
    8
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
   10
 

In [60]:
size(y)

ans =

   5000      1

